# Generated by Django 5.2.5 on 2025-08-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_roll',
            field=models.IntegerField(),
        ),
    ]
