# Generated by Django 5.2.5 on 2025-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_contact',
            field=models.BigIntegerField(default='0000000000'),
            preserve_default=False,
        ),
    ]
